import TemplateAuth from "./layouts/template_auth";
import RecipeReviewCard from "./components/CustomCard";
import Grid from "@mui/material/Grid";

import Button from "@mui/material/Button";

export const metadata = {
  title: "The Home Page",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <TemplateAuth>
      <Grid container spacing={3}>
        {[...new Array(6)].map((_, i) => (
          <Grid item xs={4} key={i}>
            <RecipeReviewCard increment={i} />
          </Grid>
        ))}
      </Grid>
    </TemplateAuth>
  );
}
